<a href="/users">Пользователи</a>
<p>
    <?php if (isset($errors['idExists'])): ?>
        <div><?= $errors['idExists'] ?></div>
    <?php endif ?>
</p>
<form action="/users/<?= $user['id'] ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <p>
        <div>
            <label>
                Имя
                <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
            </label>
            <?php if (isset($errors['name'])): ?>
                <div><?= $errors['name'] ?></div>
            <?php endif ?>
        </div>
    </p>
    <p>
        <div>
            <label>
                Email
                <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
            </label>
            <?php if (isset($errors['email'])): ?>
                <div><?= $errors['email'] ?></div>
            <?php endif ?>
        </div>
    </p>
    <p>
        <div>
            <label>
                Id
                <input type="text" name="user[id]" value="<?= htmlspecialchars($user['id']) ?>" readonly >
            </label>
            <?php if (isset($errors['id'])): ?>
                <div><?= $errors['id'] ?></div>
            <?php endif ?>
        </div>
    </p>
    <input type="submit" value="Update">
</form>