<?php if (count($flash) > 0): ?>
  <ul>
  <?php foreach ($flash as $messages): ?>
      <?php foreach ($messages as $message): ?>
          <li><?= $message ?></li>
      <?php endforeach ?>
  <?php endforeach ?>
  </ul>
<?php endif ?>

<p>
    <a href="/users/new">Новый пользователь</a>
</p>
<p>
    <form action="/users" method="get">
        <input type="search" required name="term">
    </form>
</p>
<p>
    <div>
        <?php foreach ($users as ['id' => $id, 'name' => $name]): ?>
            <form action="/users/<?= $id ?>" method="post">
                <input type="hidden" name="_METHOD" value="DELETE">
                <p>
                    <div>
                        <button> Remove </button>
                        <?= "<a href='/users/{$id}'>" . htmlspecialchars($name) . "</a>" ?>
                    </div>
                </p>
            </form>
        <?php endforeach ?>
    </div>
</p>
