<p>
    <a href="/users/new">Новый пользователь</a>
</p>
<p>
    <form action="/users" method="get">
        <input type="search" required name="term">
    </form>
</p>
<p>
    <div>
        <?php foreach ($users as ['name' => $name, 'id' => $id]): ?>
            <div>
                    <?php echo "<a href='/users/{$id}'>{$name}</a>" ?>
            </div>
        <?php endforeach ?>
    </div>
</p>
