<a href="/users">Пользователи</a>

<form action="/users" method="post">
    <p>
        <div>
            <label>
                Имя
                <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>">
            </label>
            <?php if (isset($errors['nickname'])): ?>
                <div><?= $errors['nickname'] ?></div>
            <?php endif ?>
        </div>
    </p>
    <p>
        <div>
            <label>
                Email
                <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
            </label>
            <?php if (isset($errors['email'])): ?>
                <div><?= $errors['email'] ?></div>
            <?php endif ?>
        </div>
    </p>
    <p>
        <div>
            <label>
                Id
                <input type="id" required name="user[id]" value="<?= htmlspecialchars($user['id']) ?>">
            </label>
            <?php if (isset($errors['id'])): ?>
                <div><?= $errors['id'] ?></div>
            <?php endif ?>
        </div>
    </p>
    <input type="submit" value="Sign Up">
</form>
