<?php if (count($flash) > 0): ?>
  <ul>
  <?php foreach ($flash as $messages): ?>
      <?php foreach ($messages as $message): ?>
          <li><?= $message ?></li>
      <?php endforeach ?>
  <?php endforeach ?>
  </ul>
<?php endif ?>

<p>
    <a href="/users">Пользователи</a>
</p>
<p>
    <?php  ['name' => $name, 'email' => $email, 'id' => $id] = $user ?>
    <div>
        <?= "ID - " . htmlspecialchars($id)?>
    </div>
    <div>
        <?= "Name - " . htmlspecialchars($name) ?>
    </div>
    <div>
        <?= "email - " . htmlspecialchars($email) ?>
    </div>
</p>
<p>
    <?= "<a href=/users/{$id}/edit>Редактировать профиль</a>" ?>
</p>
